#from django.db import models
from django.contrib.gis.db import models

class HhSurvey(models.Model):
    indexno = models.IntegerField(blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    nepaliname = models.CharField(max_length=255, blank=True, null=True)
    englishname = models.CharField(max_length=255, blank=True, null=True)
    fathersname = models.CharField(max_length=255, blank=True, null=True)
    mothersname = models.CharField(max_length=255, blank=True, null=True)
    grandfathersname = models.CharField(max_length=255, blank=True, null=True)
    grandmothersname = models.CharField(max_length=255, blank=True, null=True)
    nooffamilymember = models.IntegerField(blank=True, null=True)
    photoofhhh = models.BinaryField(blank=True, null=True)
    houseno = models.FloatField(blank=True, null=True)
    tole = models.CharField(max_length=255, blank=True, null=True)
    wardno = models.FloatField(blank=True, null=True)
    phonenumber = models.CharField(max_length=255, blank=True, null=True)
    medicaltreatment_choice_one = models.CharField(max_length=255, blank=True, null=True)
    medicaltreatment_choice_two = models.CharField(max_length=255, blank=True, null=True)
    medicaltreatment_choice_three = models.CharField(max_length=255, blank=True, null=True)
    pregnantmember_regular_medics_consultation = models.CharField(max_length=255, blank=True, null=True)
    childbirthplace_within_one_year = models.CharField(max_length=255, blank=True, null=True)
    childbirth_death_afterdelivery_or_within_six_weeks = models.CharField(max_length=10, blank=True, null=True)
    child_death_within_four_weeks = models.CharField(max_length=10, blank=True, null=True)
    no_of_dead_children_within_four_weeks = models.IntegerField(blank=True, null=True)
    child_death_from_four_weeks_to_a_year = models.CharField(max_length=10, blank=True, null=True)
    no_of_dead_children_four_to_a_year_time = models.IntegerField(blank=True, null=True)
    below_five_yrs_vaccinated_with_bcg_dpt_measles = models.CharField(max_length=10, blank=True, null=True)
    landuse_for_agri_livestock = models.CharField(max_length=10, blank=True, null=True)
    land_area_owned = models.IntegerField(blank=True, null=True)
    family_land_area = models.IntegerField(blank=True, null=True)
    land_area_for_food_crop = models.CharField(max_length=255, blank=True, null=True)
    enoughirrigation_in_cultivationarea = models.CharField(max_length=10, blank=True, null=True)
    land_area_irrigated_throughout_year = models.IntegerField(blank=True, null=True)
    source_of_irrigation = models.CharField(max_length=255, blank=True, null=True)
    src_of_irri_canal = models.IntegerField(blank=True, null=True)
    src_of_irri_tubewell = models.IntegerField(blank=True, null=True)
    src_of_irri_deepboring = models.IntegerField(blank=True, null=True)
    src_of_irri_dripirrigation = models.IntegerField(blank=True, null=True)
    src_of_irri_springcall = models.IntegerField(blank=True, null=True)
    src_of_irri_rainwater = models.IntegerField(blank=True, null=True)
    src_of_irri_plasticpond = models.IntegerField(blank=True, null=True)
    src_of_irri_sluice = models.IntegerField(blank=True, null=True)
    src_of_irri_drainage = models.IntegerField(blank=True, null=True)
    ownership_of_house_residing = models.CharField(max_length=255, blank=True, null=True)
    house_construction_type = models.CharField(max_length=255, blank=True, null=True)
    house_storey = models.IntegerField(blank=True, null=True)
    area_covered_by_house = models.IntegerField(blank=True, null=True)
    year_constructed = models.CharField(max_length=255, blank=True, null=True)
    house_design_approved = models.CharField(max_length=10, blank=True, null=True)
    source_of_drinkingwater = models.CharField(max_length=255, blank=True, null=True)
    src_of_dw_pipedwater_insidehouse = models.IntegerField(blank=True, null=True)
    src_of_dw_pipedwater_outsidehouse = models.IntegerField(blank=True, null=True)
    src_of_dw_deepboring = models.IntegerField(blank=True, null=True)
    src_of_dw_tubewell = models.IntegerField(blank=True, null=True)
    src_of_dw_handpump = models.IntegerField(blank=True, null=True)
    src_of_dw_well = models.IntegerField(blank=True, null=True)
    src_of_dw_openwell = models.IntegerField(blank=True, null=True)
    src_of_dw_watersource = models.IntegerField(blank=True, null=True)
    src_of_dw_river = models.IntegerField(blank=True, null=True)
    src_of_dw_jarbottled = models.IntegerField(blank=True, null=True)
    purify_water_before_drinking = models.CharField(max_length=10, blank=True, null=True)
    techniques_for_water_purification = models.CharField(max_length=255, blank=True, null=True)
    boiling = models.IntegerField(blank=True, null=True)
    chlorine_or_pius = models.IntegerField(blank=True, null=True)
    water_filter = models.IntegerField(blank=True, null=True)
    sodis_filter = models.IntegerField(blank=True, null=True)
    cooking_fule = models.CharField(max_length=255, blank=True, null=True)
    cooking_wood = models.IntegerField(blank=True, null=True)
    cooking_kerosene = models.IntegerField(blank=True, null=True)
    cooking_lpgas = models.IntegerField(blank=True, null=True)
    cooking_electricity = models.IntegerField(blank=True, null=True)
    cooking_biogas = models.IntegerField(blank=True, null=True)
    cooking_guitha = models.IntegerField(blank=True, null=True)
    stove_used_at_home = models.CharField(max_length=255, blank=True, null=True)
    stove_mud = models.IntegerField(blank=True, null=True)
    stove_improved_smokeless = models.IntegerField(blank=True, null=True)
    stove_vushe = models.IntegerField(blank=True, null=True)
    stove_kerosene = models.IntegerField(blank=True, null=True)
    stove_gastove = models.IntegerField(blank=True, null=True)
    stove_induction = models.IntegerField(blank=True, null=True)
    source_of_light = models.CharField(max_length=255, blank=True, null=True)
    electricity_source = models.CharField(max_length=255, blank=True, null=True)
    metered_connection = models.CharField(max_length=10, blank=True, null=True)
    toilet_type = models.CharField(max_length=255, blank=True, null=True)
    toilet_connected_to_publicdrainage = models.IntegerField(blank=True, null=True)
    toilet_flush_with_septictank = models.IntegerField(blank=True, null=True)
    toilet_simple = models.IntegerField(blank=True, null=True)
    toilet_temporary = models.IntegerField(blank=True, null=True)
    toilet_public = models.IntegerField(blank=True, null=True)
    toilet_notoilet = models.IntegerField(blank=True, null=True)
    income_from_agriculture = models.IntegerField(blank=True, null=True)
    income_from_business = models.IntegerField(blank=True, null=True)
    income_from_industry = models.IntegerField(blank=True, null=True)
    income_from_job = models.IntegerField(blank=True, null=True)
    income_from_remittence = models.IntegerField(blank=True, null=True)
    income_from_rent = models.IntegerField(blank=True, null=True)
    income_from_enterprenureship = models.IntegerField(blank=True, null=True)
    income_from_othersource = models.IntegerField(blank=True, null=True)
    expense_from_food = models.IntegerField(blank=True, null=True)
    expense_from_education = models.IntegerField(blank=True, null=True)
    expense_from_health = models.IntegerField(blank=True, null=True)
    expense_from_taxandservices = models.IntegerField(blank=True, null=True)
    expense_from_enterandtravel = models.IntegerField(blank=True, null=True)
    expense_from_socialwork = models.IntegerField(blank=True, null=True)
    expense_from_loanpayment = models.IntegerField(blank=True, null=True)
    expense_from_donation = models.IntegerField(blank=True, null=True)
    expense_from_othersexpense = models.IntegerField(blank=True, null=True)
    serviceconsumed_radio = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_televison = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_landlinetelephone = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_mobile = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_smartphone = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_tablet = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_computer = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_laptop = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_internet = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_motorcycle = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_car = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_refrigerator = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_washingmachine = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_airconditioner = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_transportvehicle = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_tracktor = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_waterfilter = models.CharField(max_length=10, blank=True, null=True)
    serviceconsumed_electricfan = models.CharField(max_length=10, blank=True, null=True)
    cattle_rearing = models.CharField(max_length=10, blank=True, null=True)
    number_of_ponds = models.IntegerField(blank=True, null=True)
    area_of_pond = models.IntegerField(blank=True, null=True)
    yearly_fish_production = models.IntegerField(blank=True, null=True)
    number_of_beehive = models.IntegerField(blank=True, null=True)
    beehive_type = models.CharField(max_length=255, blank=True, null=True)
    yearly_honey_production = models.IntegerField(blank=True, null=True)
    silkworm_cocoons_number = models.IntegerField(blank=True, null=True)
    silk_production = models.IntegerField(blank=True, null=True)
    type_of_healthfacility = models.CharField(max_length=255, blank=True, null=True)
    nearest_healthfacility = models.CharField(max_length=255, blank=True, null=True)
    time_to_reach_nearest_healthfacility = models.IntegerField(blank=True, null=True)
    medium_to_reach_nearest_healthfacility = models.CharField(max_length=255, blank=True, null=True)
    nearest_education_institute = models.CharField(max_length=255, blank=True, null=True)
    time_to_reach_nearest_educationfacility = models.IntegerField(blank=True, null=True)
    medium_to_reach_nearest_educationfacility = models.CharField(max_length=255, blank=True, null=True)
    solid_waste_management_site = models.CharField(max_length=255, blank=True, null=True)
    solid_waste_river = models.IntegerField(blank=True, null=True)
    solid_waste_stream = models.IntegerField(blank=True, null=True)
    solid_waste_roadside = models.IntegerField(blank=True, null=True)
    solid_waste_dumpingsite = models.IntegerField(blank=True, null=True)
    solid_waste_housecompund = models.IntegerField(blank=True, null=True)
    solid_waste_compostebin = models.IntegerField(blank=True, null=True)
    solid_waste_publicplace = models.IntegerField(blank=True, null=True)
    solid_waste_anywhere = models.IntegerField(blank=True, null=True)
    drainage_facility_at_home = models.CharField(max_length=255, blank=True, null=True)
    nodrainage_water_waste_mgmt_place = models.CharField(max_length=255, blank=True, null=True)
    nodrainage_river = models.IntegerField(blank=True, null=True)
    nodrainage_stream = models.IntegerField(blank=True, null=True)
    nodrainage_road = models.IntegerField(blank=True, null=True)
    nodrainage_inside_housecompund = models.IntegerField(blank=True, null=True)
    nodrainage_kitchengarden = models.IntegerField(blank=True, null=True)
    social_financial_participation = models.CharField(max_length=255, blank=True, null=True)
    female_in_social_org = models.CharField(max_length=10, blank=True, null=True)
    female_in_social_org_name = models.CharField(max_length=255, blank=True, null=True)
    female_in_tole_devlpmnt_inst = models.IntegerField(blank=True, null=True)
    female_in_agri_grp = models.IntegerField(blank=True, null=True)
    female_in_yuth_grp = models.IntegerField(blank=True, null=True)
    female_in_club = models.IntegerField(blank=True, null=True)
    female_in_consumer_committee = models.IntegerField(blank=True, null=True)
    female_in_schl_mgmt_committee = models.IntegerField(blank=True, null=True)
    female_in_drnk_water_consum_grp = models.IntegerField(blank=True, null=True)
    female_in_forest_consum_grp = models.IntegerField(blank=True, null=True)
    female_in_mother_grp = models.IntegerField(blank=True, null=True)
    female_in_cooperative = models.IntegerField(blank=True, null=True)
    natural_calamity_risk = models.CharField(max_length=255, blank=True, null=True)
    natural_calamity_risk_flood = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_landslide = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_fire = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_epidemic = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_wind = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_lightning = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_rivererosion = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_drought = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_winterwave = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_earthquake = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_hail = models.IntegerField(blank=True, null=True)
    natural_calamity_risk_none = models.IntegerField(blank=True, null=True)
    affected_by_natural_calamity_this_year = models.CharField(max_length=40, blank=True, null=True)
    decision_abt_household_subjects_takenby = models.CharField(max_length=255, blank=True, null=True)
    household_work_involvement = models.CharField(max_length=255, blank=True, null=True)
    bank_acc_operation = models.CharField(max_length=255, blank=True, null=True)
    consumer_committee_participation = models.CharField(max_length=255, blank=True, null=True)
    school_mgmt_committee_participation = models.CharField(max_length=255, blank=True, null=True)
    industry_business_involvement = models.CharField(max_length=255, blank=True, null=True)
    registered_as_taxpayer = models.CharField(max_length=255, blank=True, null=True)
    pan_number = models.IntegerField(blank=True, null=True)
    geography_location = models.PointField(geography=True, blank=True, null=True)
    hh_id = models.AutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'hh_survey'
