# Generated by Django 4.2.13 on 2024-06-03 23:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='househead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='')),
                ('tole', models.CharField(max_length=250)),
                ('wardno', models.PositiveSmallIntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
    ]
