# Generated by Django 4.2.13 on 2024-06-04 03:10

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'householdlocation.json'

def load_data(apps, schema_editor):
        househead = apps.get_model('household', 'househead')
        jsonfile = Path(__file__).parents[2] / DATA_FILENAME 
        
        with open(str(jsonfile)) as datafile: 
            objects = json.load(datafile)
            for obj in objects['features']:
                try:
                    objType = obj['type']
                    if objType == 'Point':
                        properties = obj['properties']
                        name = properties.get('Name in Block Letter', 'no-name')
                        longitude = obj.get('_start-geopoint_longitude',0)
                        latitude = obj.get('_start-geopoint_latitude',0)
                        photo = obj.get('Photo of Household Head or information provider_URL', 'no-photo')
                        wardno = obj.get('Ward Number', 0)
                        phone = obj.get('Phone Number', 0)
                        location = fromstr(f'POINT({longitude}{latitude})', srid=4326)
                        househead(name=name, location=location, photo=photo, wardno=wardno, phone=phone).save()
                except KeyError:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]

    
    
    
                        
                    